# Generated by Django 4.0.5 on 2022-06-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='nombre',
            new_name='codigo',
        ),
    ]
