# Generated by Django 4.0.5 on 2022-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_remove_producto_id_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='id_sku'),
        ),
    ]
